/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário - Test 1");
        getContentPane().setLayout(null);

        lblMatricula.setText("Matrícula:");
        getContentPane().add(lblMatricula);
        lblMatricula.setBounds(10, 0, 60, 30);
        getContentPane().add(txtMatricula);
        txtMatricula.setBounds(70, 0, 100, 30);

        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 40, 60, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(70, 40, 200, 30);

        lblCargo.setText("Cargo:");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(10, 80, 60, 30);
        getContentPane().add(txtCargo);
        txtCargo.setBounds(70, 80, 200, 30);

        lblSalario.setText("Salario:");
        getContentPane().add(lblSalario);
        lblSalario.setBounds(10, 120, 60, 30);
        getContentPane().add(txtSalario);
        txtSalario.setBounds(70, 120, 100, 30);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(150, 210, 110, 40);

        btnSalvar1.setText("Consultar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar1);
        btnSalvar1.setBounds(190, 0, 90, 30);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         try {
           final Connection con; //Varivel responsalvel pela Conexão (final é uma constante ou seja não pode ser alterado , diferente de uma variavel)
            Statement st;   // Variael que insere dados na tabela com comando sql
            Class.forName("com.mysql.jdbc.Driver"); //  indica o endereço do driver
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/controle","root","");// responsavel pela indicação do endereço do banco de dados e loggin no banco
            st = con.createStatement(); // cria uma sessão com o banco, autorização para execução de comandos sql
            st.executeUpdate("insert into tb_funcionario values('"+txtMatricula.getText()+"','"+txtNome.getText()+"','"+txtCargo.getText()+"',"+Double.parseDouble(txtSalario.getText())+")"); // Executa comando sql
            JOptionPane.showMessageDialog(null,"Funcionario Cadastrado com Sucesso");
            LimparCampos(); // chame classe limpar campos do formulario
         } catch (ClassNotFoundException ex) { // tratamento de erro caso o driver nao seja encontrado
            JOptionPane.showMessageDialog(null,"O Driver não esta na Biblioteca");
        } catch (SQLException ex) { // tratamento de erro caso login ou endereço do banco de dados esteja incorreto
            JOptionPane.showMessageDialog(null,"Erro nas operações no Banco de Dados");

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void LimparCampos(){
            
            txtMatricula.setText(""); //limpa campo, insere texto vazio
            txtNome.setText(""); //limpa campo, insere texto vazio
            txtCargo.setText(""); //limpa campo, insere texto vazio
            txtSalario.setText(""); //limpa campo, insere texto vazio
            txtMatricula.requestFocus(); //pede foco do formulario, inicia o cursor
}
    
    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
